In [193]:
import pandas as pd
import numpy as np
import os
from pathlib import Path
from dotenv import load_dotenv

## Load configuration

In [194]:
# Load env path
ENV_PATH = Path.cwd().parent / ".env"
load_dotenv(dotenv_path=ENV_PATH)

# Connect to database
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")

## Load database

In [195]:
from sqlalchemy import create_engine, text

# Create a connection to the PostgreSQL database
def get_db_dataframe():
    try:
        engine = create_engine(f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}")

        # Read database from query
        df = pd.read_sql_query("SELECT * FROM engineering.supermarket;", engine)
        return df
    
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None
    
# Read database
pd.set_option('display.max_columns', None)
df = get_db_dataframe()
df

,id,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,unit_price,profit_margin
0,1,AG-2011-2040,2011-01-01,2011-06-01,3,751,0,255,2,1,0,OFF-TEN-10000025,1,14,3413,4080000.0,2,0.0,1061400.0,354600.0,3,2011,2040000.0,2600.0
1,2,IN-2011-47883,2011-01-01,2011-08-01,3,398,0,702,6,0,9,OFF-SU-10000618,1,15,168,1200000.0,3,0.1,360360.0,97200.0,3,2011,400000.0,3000.0
2,3,HU-2011-1220,2011-01-01,2011-05-01,2,48,0,175,56,3,5,OFF-TEN-10001585,1,14,3382,660000.0,4,0.0,296400.0,81700.0,1,2011,165000.0,4500.0
3,4,IT-2011-3647632,2011-01-01,2011-05-01,2,275,2,939,123,4,7,OFF-PA-10001492,1,12,1330,450000.0,3,0.5,-260550.0,48200.0,1,2011,150000.0,-5800.0
4,5,CA-2011-1510,2011-02-01,2011-06-01,3,483,0,748,22,2,1,TEC-OKI-10002750,2,11,2662,3140000.0,1,0.0,31200.0,241000.0,3,2011,3140000.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25030,25031,CA-2014-115427,2014-12-12,2015-04-01,3,264,1,192,139,6,12,OFF-BI-10004632,1,3,1488,210000.0,2,0.2,64750.0,20600.0,3,2014,105000.0,3100.0
25031,25032,UP-2014-4410,2014-12-12,2015-04-01,3,316,0,1082,136,3,5,OFF-AVE-10003558,1,10,469,280000.0,4,0.0,61200.0,17000.0,3,2014,70000.0,2200.0
25032,25033,MX-2014-108574,2014-12-12,2015-04-01,3,402,2,964,81,5,7,OFF-LA-10004969,1,10,2534,170000.0,3,0.0,6600.0,13200.0,3,2014,56700.0,400.0
25033,25034,MO-2014-2560,2014-12-12,2015-05-01,3,472,0,923,85,1,0,OFF-WIL-10001069,1,3,3541,40000.0,1,0.0,4200.0,4900.0,3,2014,40000.0,1000.0
25034,25035,CA-2014-156720,2014-12-12,2015-04-01,3,371,0,251,139,6,12,OFF-FA-10003472,1,8,515,30000.0,3,0.2,-6048.0,1700.0,3,2014,10000.0,-2000.0

In [196]:
DB = Path.cwd().parent / "app" / "data" / "cleaned" / "sql_supermarket.parquet"
df = pd.read_parquet(DB)
df

,id,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,unit_price,profit_margin
0,1,AG-2011-2040,2011-01-01,2011-06-01,3,751,0,255,2,1,0,OFF-TEN-10000025,1,14,3413,4080000.0,2,0.0,1061400.0,354600.0,3,2011,2040000.0,2600.0
1,2,IN-2011-47883,2011-01-01,2011-08-01,3,398,0,702,6,0,9,OFF-SU-10000618,1,15,168,1200000.0,3,0.1,360360.0,97200.0,3,2011,400000.0,3000.0
2,3,HU-2011-1220,2011-01-01,2011-05-01,2,48,0,175,56,3,5,OFF-TEN-10001585,1,14,3382,660000.0,4,0.0,296400.0,81700.0,1,2011,165000.0,4500.0
3,4,IT-2011-3647632,2011-01-01,2011-05-01,2,275,2,939,123,4,7,OFF-PA-10001492,1,12,1330,450000.0,3,0.5,-260550.0,48200.0,1,2011,150000.0,-5800.0
4,5,CA-2011-1510,2011-02-01,2011-06-01,3,483,0,748,22,2,1,TEC-OKI-10002750,2,11,2662,3140000.0,1,0.0,31200.0,241000.0,3,2011,3140000.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25030,25031,CA-2014-115427,2014-12-12,2015-04-01,3,264,1,192,139,6,12,OFF-BI-10004632,1,3,1488,210000.0,2,0.2,64750.0,20600.0,3,2014,105000.0,3100.0
25031,25032,UP-2014-4410,2014-12-12,2015-04-01,3,316,0,1082,136,3,5,OFF-AVE-10003558,1,10,469,280000.0,4,0.0,61200.0,17000.0,3,2014,70000.0,2200.0
25032,25033,MX-2014-108574,2014-12-12,2015-04-01,3,402,2,964,81,5,7,OFF-LA-10004969,1,10,2534,170000.0,3,0.0,6600.0,13200.0,3,2014,56700.0,400.0
25033,25034,MO-2014-2560,2014-12-12,2015-05-01,3,472,0,923,85,1,0,OFF-WIL-10001069,1,3,3541,40000.0,1,0.0,4200.0,4900.0,3,2014,40000.0,1000.0
25034,25035,CA-2014-156720,2014-12-12,2015-04-01,3,371,0,251,139,6,12,OFF-FA-10003472,1,8,515,30000.0,3,0.2,-6048.0,1700.0,3,2014,10000.0,-2000.0

In [205]:
# Check data duplicate on subset order_id
df.duplicated(subset=['order_id']).sum()

0

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25035 entries, 0 to 25034
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              25035 non-null  int64
 1   order_id        25035 non-null  object
 2   order_date      25035 non-null  datetime64[ns]
 3   ship_date       25035 non-null  datetime64[ns]
 4   ship_mode       25035 non-null  object
 5   customer_name   25035 non-null  object
 6   segment         25035 non-null  object
 7   state           25035 non-null  object
 8   country         25035 non-null  object
 9   market          25035 non-null  object
 10  region          25035 non-null  object
 11  product_id      25035 non-null  object
 12  category        25035 non-null  object
 13  sub_category    25035 non-null  object
 14  product_name    25035 non-null  object
 15  sales           25035 non-null  float64
 16  quantity        25035 non-null  int64
 17  discount        25035 non-null  float64
 18  profit          25035 non-null  float64
 19  shipping_cost   25035 non-null  float64
 20  order_priority  25035 non-null  object
 21  year            25035 non-null  int64
 22  unit_price      25035 non-null  float64
 23  profit_margin   25035 non-null  float64
dtypes: datetime64[ns](2), float64(6), int64(3), object(13)
memory usage: 4.6+ MB

In [199]:
# Transform profit margin into percentage
df['profit_margin'] = df['profit_margin'] / 100
df

,id,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,unit_price,profit_margin
0,1,AG-2011-2040,2011-01-01,2011-06-01,3,751,0,255,2,1,0,OFF-TEN-10000025,1,14,3413,4080000.0,2,0.0,1061400.0,354600.0,3,2011,2040000.0,26.0
1,2,IN-2011-47883,2011-01-01,2011-08-01,3,398,0,702,6,0,9,OFF-SU-10000618,1,15,168,1200000.0,3,0.1,360360.0,97200.0,3,2011,400000.0,30.0
2,3,HU-2011-1220,2011-01-01,2011-05-01,2,48,0,175,56,3,5,OFF-TEN-10001585,1,14,3382,660000.0,4,0.0,296400.0,81700.0,1,2011,165000.0,45.0
3,4,IT-2011-3647632,2011-01-01,2011-05-01,2,275,2,939,123,4,7,OFF-PA-10001492,1,12,1330,450000.0,3,0.5,-260550.0,48200.0,1,2011,150000.0,-58.0
4,5,CA-2011-1510,2011-02-01,2011-06-01,3,483,0,748,22,2,1,TEC-OKI-10002750,2,11,2662,3140000.0,1,0.0,31200.0,241000.0,3,2011,3140000.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25030,25031,CA-2014-115427,2014-12-12,2015-04-01,3,264,1,192,139,6,12,OFF-BI-10004632,1,3,1488,210000.0,2,0.2,64750.0,20600.0,3,2014,105000.0,31.0
25031,25032,UP-2014-4410,2014-12-12,2015-04-01,3,316,0,1082,136,3,5,OFF-AVE-10003558,1,10,469,280000.0,4,0.0,61200.0,17000.0,3,2014,70000.0,22.0
25032,25033,MX-2014-108574,2014-12-12,2015-04-01,3,402,2,964,81,5,7,OFF-LA-10004969,1,10,2534,170000.0,3,0.0,6600.0,13200.0,3,2014,56700.0,4.0
25033,25034,MO-2014-2560,2014-12-12,2015-05-01,3,472,0,923,85,1,0,OFF-WIL-10001069,1,3,3541,40000.0,1,0.0,4200.0,4900.0,3,2014,40000.0,10.0
25034,25035,CA-2014-156720,2014-12-12,2015-04-01,3,371,0,251,139,6,12,OFF-FA-10003472,1,8,515,30000.0,3,0.2,-6048.0,1700.0,3,2014,10000.0,-20.0

## Feature engineering

In [200]:
# Calculate underlying helper metrics to ensure feature engineering
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])
df['shipping_days'] = (df['ship_date'] -  df['order_date']).dt.days

# Define a function to calculate fraud condition on column factors
condition_massive_loss = (df['discount'] >= 0.4) & (df['profit_margin'] <= -1.8)
condition_bulk_anomaly = (df['quantity'] > df['quantity'].quantile(0.99)) & (df['profit'] < 0)
condition_shipping_error = df['shipping_days'] < 0

In [201]:
# Combine condition to create the binary fraud label
df['fraud'] = np.where(condition_massive_loss | condition_bulk_anomaly | condition_shipping_error, 1, 0)
print(df["fraud"].value_counts(normalize=True))

fraud
0    0.583383
1    0.416617
Name: proportion, dtype: float64

## Data is clean

In [206]:
df['profit_margin']

0        26.0
1        30.0
2        45.0
3       -58.0
4         1.0
         ...
25030    31.0
25031    22.0
25032     4.0
25033    10.0
25034   -20.0
Name: profit_margin, Length: 25035, dtype: float64

## Split data into X and y

In [203]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['fraud', 'order_id', 'order_date', 'ship_date', 'product_id', 'id'])
y = df['fraud']

## Data encoding