In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
from pathlib import Path

In [2]:
pd.set_option('display.max_columns', None)
SALES_DIR = Path.cwd().parent / "app" / "data" / "cleaned" / "sql_supermarket.parquet"
FRAUD_DIR = Path.cwd().parent / "app" / "data" / "cleaned" / "fraud_sql_supermarket.parquet"

In [3]:
df_sales = pd.read_parquet(SALES_DIR)
df_sales.head(3)

,id,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,unit_price,profit_margin
0,1,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",4080000.0,2,0.0,1061400.0,354600.0,Medium,2011,2040000.0,0.26
1,2,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",1200000.0,3,0.1,360360.0,97200.0,Medium,2011,400000.0,0.30
2,3,HU-2011-1220,2011-01-01,2011-05-01,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",660000.0,4,0.0,296400.0,81700.0,High,2011,165000.0,0.45

In [4]:
df_fraud = pd.read_parquet(FRAUD_DIR)
df_fraud.head(3)

,id,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,unit_price,profit_margin,shipping_days,fraud
0,1,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",4080000.0,2,0.0,1061400.0,354600.0,Medium,2011,2040000.0,0.26,151,0
1,2,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",1200000.0,3,0.1,360360.0,97200.0,Medium,2011,400000.0,0.30,212,0
2,3,HU-2011-1220,2011-01-01,2011-05-01,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",660000.0,4,0.0,296400.0,81700.0,High,2011,165000.0,0.45,120,0

In [5]:
df_fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25035 entries, 0 to 25034
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              25035 non-null  int64
 1   order_id        25035 non-null  object
 2   order_date      25035 non-null  datetime64[ns]
 3   ship_date       25035 non-null  datetime64[ns]
 4   ship_mode       25035 non-null  object
 5   customer_name   25035 non-null  object
 6   segment         25035 non-null  object
 7   state           25035 non-null  object
 8   country         25035 non-null  object
 9   market          25035 non-null  object
 10  region          25035 non-null  object
 11  product_id      25035 non-null  object
 12  category        25035 non-null  object
 13  sub_category    25035 non-null  object
 14  product_name    25035 non-null  object
 15  sales           25035 non-null  float64
 16  quantity        25035 non-null  int64
 17  discount        25035 non-null  float64
 18  profit          25035 non-null  float64
 19  shipping_cost   25035 non-null  float64
 20  order_priority  25035 non-null  object
 21  year            25035 non-null  int64
 22  unit_price      25035 non-null  float64
 23  profit_margin   25035 non-null  float64
 24  shipping_days   25035 non-null  int64
 25  fraud           25035 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(13)
memory usage: 5.0+ MB

## Combining data

In [6]:
df_combined = df_sales.merge(
    df_fraud[['order_id', 'shipping_days', 'fraud']],
    on='order_id',
    how='left'
)
df_combined.head()

,id,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,unit_price,profit_margin,shipping_days,fraud
0,1,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",4080000.0,2,0.0,1061400.0,354600.0,Medium,2011,2040000.0,0.26,151,0
1,2,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",1200000.0,3,0.1,360360.0,97200.0,Medium,2011,400000.0,0.30,212,0
2,3,HU-2011-1220,2011-01-01,2011-05-01,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",660000.0,4,0.0,296400.0,81700.0,High,2011,165000.0,0.45,120,0
3,4,IT-2011-3647632,2011-01-01,2011-05-01,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",450000.0,3,0.5,-260550.0,48200.0,High,2011,150000.0,-0.58,120,0
4,5,CA-2011-1510,2011-02-01,2011-06-01,Standard Class,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,TEC-OKI-10002750,Technology,Machines,"Okidata Inkjet, Wireless",3140000.0,1,0.0,31200.0,241000.0,Medium,2011,3140000.0,0.01,120,0

In [7]:
df = pd.read_parquet(Path.cwd().parent / "app" / "data" / "cleaned" / "combined_sql_supermarket.parquet")
df

,id,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,unit_price,profit_margin,shipping_days,fraud
0,1,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",4080000.0,2,0.0,1061400.0,354600.0,Medium,2011,2040000.0,0.26,151,0
1,2,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",1200000.0,3,0.1,360360.0,97200.0,Medium,2011,400000.0,0.30,212,0
2,3,HU-2011-1220,2011-01-01,2011-05-01,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",660000.0,4,0.0,296400.0,81700.0,High,2011,165000.0,0.45,120,0
3,4,IT-2011-3647632,2011-01-01,2011-05-01,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",450000.0,3,0.5,-260550.0,48200.0,High,2011,150000.0,-0.58,120,0
4,5,CA-2011-1510,2011-02-01,2011-06-01,Standard Class,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,TEC-OKI-10002750,Technology,Machines,"Okidata Inkjet, Wireless",3140000.0,1,0.0,31200.0,241000.0,Medium,2011,3140000.0,0.01,120,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25030,25031,CA-2014-115427,2014-12-12,2015-04-01,Standard Class,Erica Bern,Corporate,California,United States,US,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,210000.0,2,0.2,64750.0,20600.0,Medium,2014,105000.0,0.31,110,0
25031,25032,UP-2014-4410,2014-12-12,2015-04-01,Standard Class,Guy Thornton,Consumer,Zaporizhzhya,Ukraine,EMEA,EMEA,OFF-AVE-10003558,Office Supplies,Labels,"Avery Round Labels, Alphabetical",280000.0,4,0.0,61200.0,17000.0,Medium,2014,70000.0,0.22,110,0
25032,25033,MX-2014-108574,2014-12-12,2015-04-01,Standard Class,Julia Barnett,Home Office,Tamaulipas,Mexico,LATAM,North,OFF-LA-10004969,Office Supplies,Labels,"Novimex Legal Exhibit Labels, Adjustable",170000.0,3,0.0,6600.0,13200.0,Medium,2014,56700.0,0.04,110,0
25033,25034,MO-2014-2560,2014-12-12,2015-05-01,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,OFF-WIL-10001069,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",40000.0,1,0.0,4200.0,4900.0,Medium,2014,40000.0,0.10,140,0
25034,25035,CA-2014-156720,2014-12-12,2015-04-01,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,30000.0,3,0.2,-6048.0,1700.0,Medium,2014,10000.0,-0.20,110,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25035 entries, 0 to 25034
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              25035 non-null  int64
 1   order_id        25035 non-null  object
 2   order_date      25035 non-null  datetime64[ns]
 3   ship_date       25035 non-null  datetime64[ns]
 4   ship_mode       25035 non-null  object
 5   customer_name   25035 non-null  object
 6   segment         25035 non-null  object
 7   state           25035 non-null  object
 8   country         25035 non-null  object
 9   market          25035 non-null  object
 10  region          25035 non-null  object
 11  product_id      25035 non-null  object
 12  category        25035 non-null  object
 13  sub_category    25035 non-null  object
 14  product_name    25035 non-null  object
 15  sales           25035 non-null  float64
 16  quantity        25035 non-null  int64
 17  discount        25035 non-null  float64
 18  profit          25035 non-null  float64
 19  shipping_cost   25035 non-null  float64
 20  order_priority  25035 non-null  object
 21  year            25035 non-null  int64
 22  unit_price      25035 non-null  float64
 23  profit_margin   25035 non-null  float64
 24  shipping_days   25035 non-null  int64
 25  fraud           25035 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(13)
memory usage: 5.0+ MB